// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANjg7BKEuEAkrsI42rXmD3B2jW3ifscTk',
    appId: '1:119643993095:web:09c2eda917a1bbeef626a2',
    messagingSenderId: '119643993095',
    projectId: 'mentalbloom-app-firebase',
    authDomain: 'mentalbloom-app-firebase.firebaseapp.com',
    storageBucket: 'mentalbloom-app-firebase.firebasestorage.app',
    measurementId: 'G-4Q7WMF8PT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRI-EOlDhBzCh3chzsrssO_UzrwD6cU3U',
    appId: '1:119643993095:android:34e1611d46a8b2c2f626a2',
    messagingSenderId: '119643993095',
    projectId: 'mentalbloom-app-firebase',
    storageBucket: 'mentalbloom-app-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKf-dEfwNo7gMhEuC7NLrZxKSMF5IAuo0',
    appId: '1:119643993095:ios:6905133a0bfa21eff626a2',
    messagingSenderId: '119643993095',
    projectId: 'mentalbloom-app-firebase',
    storageBucket: 'mentalbloom-app-firebase.firebasestorage.app',
    iosBundleId: 'com.example.mentalbloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKf-dEfwNo7gMhEuC7NLrZxKSMF5IAuo0',
    appId: '1:119643993095:ios:6905133a0bfa21eff626a2',
    messagingSenderId: '119643993095',
    projectId: 'mentalbloom-app-firebase',
    storageBucket: 'mentalbloom-app-firebase.firebasestorage.app',
    iosBundleId: 'com.example.mentalbloom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANjg7BKEuEAkrsI42rXmD3B2jW3ifscTk',
    appId: '1:119643993095:web:192d609fc9ceb4c9f626a2',
    messagingSenderId: '119643993095',
    projectId: 'mentalbloom-app-firebase',
    authDomain: 'mentalbloom-app-firebase.firebaseapp.com',
    storageBucket: 'mentalbloom-app-firebase.firebasestorage.app',
    measurementId: 'G-TM28X7Q0X4',
  );
}
